### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by bdeak4** [nk38104/timetabler#1]
This project uses same name as commercial alternative (https://www.timetabler.com/) without explicit permission thus producing copyright infringement.

To prevent legal actions from Timetabler LLC, please rename project to "raspore2ar".

Best regards

**Comment by nkelava** [comment]
Thank you for your concern, I really appreciate it. Although, I don't think there would be an issue because I searched on TESS and couple of more sites and if I'm not wrong it is not trademarked. Furthermore, this is just an internship project and I don't intend to go commercial with it so I don't think it will cause problems. But, because I'm not familiar with law, better safe than sorry, I renamed the project. Didn't go with your suggestion unfortunately.

Best regards
